// The display order is the learning order: an exercise only uses ideas that
// are introduced in this lesson or an earlier one.
window.ROADMAP_ORDER = [
  "firstProgram",
  "consolePractice",
  "variables",
  "dataTypes",
  "values",
  "operators",
  "conditionals",
  "functions",
  "arrowFunctions",
  "arrays",
  "loops",
  "fizzBuzz",
  "foundationRecap",
  "objects",
  "scope",
  "scopeClosures",
  "arrayMethods",
  "es6",
  "stringMethods",
  "domEvents",
  "formsValidation",
  "debuggingTools",
  "async",
  "modulesErrors",
  "apisData",
  "jsonData",
  "browserStorage",
  "thisKeyword",
  "objectsPrototypes",
  "webAppRecap",
  "foundationProjects",
  "professionalPractice",
  "gitBasics",
]
